// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gimli/Internal/proto-files/service/shortener-service.proto

package domain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FullURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *FullURL) Reset() {
	*x = FullURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullURL) ProtoMessage() {}

func (x *FullURL) ProtoReflect() protoreflect.Message {
	mi := &file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullURL.ProtoReflect.Descriptor instead.
func (*FullURL) Descriptor() ([]byte, []int) {
	return file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescGZIP(), []int{0}
}

func (x *FullURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ShortPath) Reset() {
	*x = ShortPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortPath) ProtoMessage() {}

func (x *ShortPath) ProtoReflect() protoreflect.Message {
	mi := &file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortPath.ProtoReflect.Descriptor instead.
func (*ShortPath) Descriptor() ([]byte, []int) {
	return file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescGZIP(), []int{1}
}

func (x *ShortPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_gimli_Internal_proto_files_service_shortener_service_proto protoreflect.FileDescriptor

var file_gimli_Internal_proto_files_service_shortener_service_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x67, 0x69, 0x6d, 0x6c, 0x69, 0x2f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x1b, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x32, 0x64, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12,
	0x2c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x1a, 0x11, 0x2e, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x0f, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x55, 0x52, 0x4c, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x6d, 0x6c,
	0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescOnce sync.Once
	file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescData = file_gimli_Internal_proto_files_service_shortener_service_proto_rawDesc
)

func file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescGZIP() []byte {
	file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescOnce.Do(func() {
		file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescData)
	})
	return file_gimli_Internal_proto_files_service_shortener_service_proto_rawDescData
}

var file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gimli_Internal_proto_files_service_shortener_service_proto_goTypes = []interface{}{
	(*FullURL)(nil),   // 0: domain.FullURL
	(*ShortPath)(nil), // 1: domain.ShortPath
}
var file_gimli_Internal_proto_files_service_shortener_service_proto_depIdxs = []int32{
	0, // 0: domain.Shortener.Create:input_type -> domain.FullURL
	1, // 1: domain.Shortener.Get:input_type -> domain.ShortPath
	1, // 2: domain.Shortener.Create:output_type -> domain.ShortPath
	0, // 3: domain.Shortener.Get:output_type -> domain.FullURL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gimli_Internal_proto_files_service_shortener_service_proto_init() }
func file_gimli_Internal_proto_files_service_shortener_service_proto_init() {
	if File_gimli_Internal_proto_files_service_shortener_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gimli_Internal_proto_files_service_shortener_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gimli_Internal_proto_files_service_shortener_service_proto_goTypes,
		DependencyIndexes: file_gimli_Internal_proto_files_service_shortener_service_proto_depIdxs,
		MessageInfos:      file_gimli_Internal_proto_files_service_shortener_service_proto_msgTypes,
	}.Build()
	File_gimli_Internal_proto_files_service_shortener_service_proto = out.File
	file_gimli_Internal_proto_files_service_shortener_service_proto_rawDesc = nil
	file_gimli_Internal_proto_files_service_shortener_service_proto_goTypes = nil
	file_gimli_Internal_proto_files_service_shortener_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShortenerClient is the client API for Shortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenerClient interface {
	Create(ctx context.Context, in *FullURL, opts ...grpc.CallOption) (*ShortPath, error)
	Get(ctx context.Context, in *ShortPath, opts ...grpc.CallOption) (*FullURL, error)
}

type shortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerClient(cc grpc.ClientConnInterface) ShortenerClient {
	return &shortenerClient{cc}
}

func (c *shortenerClient) Create(ctx context.Context, in *FullURL, opts ...grpc.CallOption) (*ShortPath, error) {
	out := new(ShortPath)
	err := c.cc.Invoke(ctx, "/domain.Shortener/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) Get(ctx context.Context, in *ShortPath, opts ...grpc.CallOption) (*FullURL, error) {
	out := new(FullURL)
	err := c.cc.Invoke(ctx, "/domain.Shortener/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServer is the server API for Shortener service.
type ShortenerServer interface {
	Create(context.Context, *FullURL) (*ShortPath, error)
	Get(context.Context, *ShortPath) (*FullURL, error)
}

// UnimplementedShortenerServer can be embedded to have forward compatible implementations.
type UnimplementedShortenerServer struct {
}

func (*UnimplementedShortenerServer) Create(context.Context, *FullURL) (*ShortPath, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedShortenerServer) Get(context.Context, *ShortPath) (*FullURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterShortenerServer(s *grpc.Server, srv ShortenerServer) {
	s.RegisterService(&_Shortener_serviceDesc, srv)
}

func _Shortener_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Shortener/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).Create(ctx, req.(*FullURL))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Shortener/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).Get(ctx, req.(*ShortPath))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shortener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domain.Shortener",
	HandlerType: (*ShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Shortener_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Shortener_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gimli/Internal/proto-files/service/shortener-service.proto",
}
